---
- name: boilerplate ubuntu settings for a webserver
  import_tasks: ubuntu-bootstrap.yml
  tags: ['ubuntu-bootstrap']

- name: create a deploy/ssh user for server maintenance
  import_tasks: deploy-user.yml
  tags: ['deploy-user']

- name: install webserver requirements for tastyigniter
  import_tasks: server-requirements.yml
  tags: ['tasty-server']

- name: set up database for tastyigniter
  import_tasks: database.yml
  tags: ['database']

- name: install tastyigniter application files
  import_tasks: tasty-app.yml
  tags: ['tasty-app']

- name: set up webserver (nginx) configuration for tastyigniter
  import_tasks: tasty-webserver.yml
  tags: ['webserver']

- name: set up certificates for TI as needed
  import_tasks: tasty-certs.yml
  when: env == 'production'
