---

- name: apt packages needed for TastyIgniter
  apt:
    package:
      - openssl
      - nginx
      - mysql-server  
      - unzip
      - acl
      - php-fpm
      - php-mysql
      - php-curl
      - php-xml
      - php-gd
      - php-mbstring
      - php-json
      - php-tokenizer
      - php-zip
      # - composer # still on composer 1 - see block below
      - python3-pip
  become: true

# on ubuntu, apt-installed composer can't self-update. Install a fresh version at > 2.0, or else uninstall composer from apt before running this script
- name: install/upgrade to composer 2 if we're not already
  block:
    - name: Check if composer exists
      stat:
        path: /usr/bin/composer
        checksum_algorithm: sha256
      register: composer_bin

    - name: Get Composer installer signature.
      uri:
        url: https://composer.github.io/installer.sig
        return_content: true
      register: composer_installer_signature
      when: not composer_bin.stat.exists

    - name: Download Composer installer.
      get_url:
        url: https://getcomposer.org/installer
        dest: /tmp/composer-installer.php
        mode: 0755
        checksum: "sha384:{{ composer_installer_signature.content }}"
      when: not composer_bin.stat.exists

    - name: Run Composer installer.
      command: >
        php composer-installer.php --install-dir=/usr/bin/
        chdir=/tmp
      when: not composer_bin.stat.exists
      become: true

    - name: Move Composer into globally-accessible location.
      command: >
        mv /usr/bin/composer.phar /usr/bin/composer
        creates=/usr/bin/composer
      when: not composer_bin.stat.exists
      become: true

    - name: Remove Composer installer
      file: 
        path: /tmp/composer-installer.php
        state: absent 


 






