---

- name: Create and install self-signed certificate for local development servers
  block:
  - name: Create private key (RSA, 4096 bits)
    community.crypto.openssl_privatekey:
      path: "/etc/ssl/certs/selfsigned-{{hostname}}.key"

  - name: Create a self-signed certificate
    community.crypto.x509_certificate:
      path: "/etc/ssl/certs/selfsigned-{{hostname}}.pem"
      privatekey_path: "/etc/ssl/certs/selfsigned-{{hostname}}.key"
      provider: selfsigned
  
  when: env == 'local'




